Significant changes in the project
fmh-charity/fmh-android pull request #1
Opened 2021-11-05 13:02 UTC by Dolgoff62

2021-11-06 21:19 UTC, maks1596 requested changes
Комментарии не дублировал. Для каждого комментария необходимо искать аналогичные места и исправлять их тоже

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +)
Спрячь глубже, чтобы не было мучительно больно при авторизации прятать. Сделай, как это было бы на самом деле. Если я всё правильно понимаю, то у тебя этот заглушечный пользователь должен всплыть где-то на уровне имплементации репозитория. Там же он и умрёт, когда появится авторизация

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +        getItem(position)?.let {
Лучше без `?`. Элемент всегда должен быть. Пускай в таком случае приложение лучше упадёт, если `getItem(position)` вернёт `null`

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +                            Utils.shortUserNameGenerator(
```suggestion
                            Utils.generateShortUserName(
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +                        claimComment.creator.middleName?.let { middleName ->
классический `if` и SmartCast сделают всё понятнее и без лишних вложенностей :wink:

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +                    claimComment.claimComment.createDate?.let {Utils.showDate(it)}
Неудачное название метода :man_shrugging: 
Как будто дата должна быть где-то показана, например, в консоли. Предложу вариант, чтобы было понятнее о чём я.
```suggestion
                    claimComment.claimComment.createDate?.let { Utils.formatDate(it) }
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +                    claimComment.claimComment.createDate?.let {Utils.showDate(it)}
то же самое и с `showTime`

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +                }
По-моему так короче будет и не менее выразительно :blush:  
```suggestion
                editLightImageButton.setImageResource(
                    if (claimComment.creator.id != user.id) R.drawable.ic_pen_light else R.drawable.ic_pen
                )
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +    class ClaimCommentDiffCallback : DiffUtil.ItemCallback<ClaimCommentWithCreator>() {
```suggestion
    prvate object DiffCallback : DiffUtil.ItemCallback<ClaimCommentWithCreator>() {
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +        }
Реализация неверная. Читать документацию к методам

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +            binding.apply {
На случай, если захочется поэкономить место и не вызвать побочных эффектов
```suggestion
        fun bind(claimComment: ClaimCommentWithCreator) = with(binding) {
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimListAdapter.kt
> +                        fullClaim.executor?.lastName.toString(),
зачем `toString` в конце? :astonished: 
чтобы от `nullability` избавиться?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimListAdapter.kt
> +                        fullClaim.executor?.lastName.toString(),
Если что, то имплементация этого `toString` примерно следующая:
```kotlin
fun String?.toString() = this ?: "this string is null"
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimListAdapter.kt
> +                themeMaterialTextView.text = fullClaim.claim.title
что-то название какое-то у `TextView` странное :thinking:

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/NewsControlPanelAdapter.kt
> +            }
Серьёзно? `if ... else` похоже теперь стал "для слабаков" :smile: 
```suggestion
            if (newsItemWithCreator.news.newsItem.publishEnabled) {
                newsItemPublishedTextView.text = itemView.context.getString(R.string.news_control_panel_active)
                newsItemPublishedIconImageView.setImageResource(R.drawable.ic_baseline_check_24)
            } else {
                newsItemPublishedTextView.text = itemView.context.getString(R.string.news_control_panel_not_active)
                newsItemPublishedIconImageView.setImageResource(R.drawable.ic_baseline_clear_24)
            }
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/NewsControlPanelAdapter.kt
> +                    else -> return
никаких "1, 2, 3..." и так далее. Переделать на `enum` или что-то около того

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/NewsControlPanelAdapter.kt
> +            )
По-моему для этого есть метод в `Utils`

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/NewsListAdapter.kt
> +        return oldItem == newItem
Неправильная имплементация

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/api/ApiModule.kt
> +        return retrofit(okhttp(loggingInterceptor()))
`loggingInterceptor()` похоже на какую-то глобальную функцию. От куда она?
Может лучше будет этот `interceptor` заинжектить в метод? :man_shrugging:

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/application/FhmApplication.kt
> +    }
В `onCreate` не ругается на бесполезное переопределение метода?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dao/ClaimDao.kt
> +    // Сортируй тут по датам дурачок :)
М?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dao/ClaimDao.kt
> +    ): Flow<List<FullClaim>>
Так не универсальнее будет?
```suggestion
    @Query("SELECT * FROM ClaimEntity WHERE status IN :statuses ORDER BY planExecuteDate ASC, createDate DESC")
    fun getClaimsInStatuses(statuses: List<Claim.Status>): Flow<List<FullClaim>>
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dao/ClaimDao.kt
> +    fun getClaimComments(claimId: Int): Flow<List<ClaimCommentWithCreator>>
К другой таблице обращаешься. Я бы в отдельный `DAO` убрал, если честно

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dao/ClaimDao.kt
> +class WishClaimStatusConverter {
Почему `Wish`?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/db/AppDb.kt
> +    abstract fun newsCategoryDao(): NewsCategoryDao
Обычно так методы не именуются. Либо поменяй `fun` на `val`, либо добавь в начале всех методов `get`

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dto/Claim.kt
> +    val deleted: Boolean = false,
Что-то мне все эти значения по умолчанию не нравятся. Можно без них обойтись?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dto/Claim.kt
> +) : Parcelable
Убери в отдельный файл. `Claim` (как мне мерещится) - это чистая модель данных, а `FullClaim` - это немного более огрязнённая деталями вытяжка из базы данных

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dto/News.kt
> +        }
чёт падазрительна :raised_eyebrow: 
Выбери либо `toString`, либо `data class`. Вместе это немного странно выглядит

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dto/SplashScreen.kt
> +data class SplashScreen(
Странное какое-то название для dto

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/claimRepository/ClaimRepository.kt
> +    val dataOpenInProgress: Flow<List<FullClaim>>
Для единообразия лучше их тоже превратить в методы

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/claimRepository/ClaimRepository.kt
> +    suspend fun getAllClaims(): List<Claim>
Непонятно чем этот метод так принципиально отличается от `data`. Ну то есть:
1. Почему `suspend`?
2. Почему возвращает `List`, а не `Flow`?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/claimRepository/ClaimRepository.kt
> +        claimComment: ClaimComment
Без комментария мне не понятно, как в смене статуса участвуют последние два аргумента

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/claimRepository/ClaimRepository.kt
> +    suspend fun saveClaim(claim: Claim): Claim
Затрудняюсь вот так сходу в интерфейсе понять чем отличаются эти два метода друг от друга?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/claimRepository/ClaimRepository.kt
> +    suspend fun getAllClaimsWithOpenAndInProgressStatus(): List<Claim>
А в чём отличие от `dataOpenInProgress`?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/newsRepository/NewsRepositoryImpl.kt
> +            .catch { e -> from(e) }
Воу-воу. Это что за `from` и зачем он?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/newsRepository/NewsRepositoryImpl.kt
> +        newsCategoryDao.insert(categories.toNewsCategoryEntity())
Может всю это грязнульку перенести в `App`? Там при старте приложения проверить что всё, что нам нужно есть, а если нет, то заинсёртить

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/userRepository/UserRepositoryImp.kt
> +        val temporaryUserList = mutableListOf(User(
Просто `listOf` уже не в моде или не подходит?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/userRepository/UserRepositoryImp.kt
> +        userDao.insert(temporaryUserList.toEntity())
На каждый вызов метода будет происходить вставка пользователей в таблицу. Зачем? Может проще при старте приложения проверить пустая ли таблица с пользователями, и если да, то заполнить таблицу

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/AppActivity.kt
> +        val bla = viewModel
Настало время убрать? :blush:

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFragment.kt
> +        val menuFiltering =
```suggestion
        val filteringMenu =
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFragment.kt
> +        mainMenu.menu.removeItem(R.id.menu_item_claims)
Я не понимаю зачем сразу удалять элемент из меню

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFragment.kt
> +                    findNavController().navigate(R.id.action_claimListFragment_to_mainFragment)
Лучше прокинуть во `viewModel`, а она уже решит что делать с этим нажатием по пункту меню

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFragment.kt
> +            containerListClaimInclude.expandMaterialButton.visibility = View.GONE
Если ничего не мешает то проще в файл с разметкой прописать
```xml
android:visibility="gone"
tools:visibility="visible"
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFragment.kt
> +            root.setBackgroundResource(R.drawable.background_app)
Что-то мешает установить задник в разметке?

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFragment.kt
> +            }
Обработка события нажатия по карточке должна быть во `viewModel`-и

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFragment.kt
> +                    adapter.submitList(state.filter { it.claim.status == Claim.Status.EXECUTED })
У тебя есть база. Фильтрация там эффективнее произойдёт

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/CreateEditClaimCommentFragment.kt
> +        }
`View` не должен знать как реагировать на события. `View` - не делегат. `View` глупая - что ей скажут, то и сделает. Поэтому эту пару событий совершенно точно можно схлопнуть до одного прямого указания "навигируемся назад", "закрываем экран". Ну, или ещё чего, на что фантазии хватит :blush:

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/CreateEditClaimCommentFragment.kt
> +        val claimId: Int = args.argClaimId
Надо все аргументы отдать во `viewModel`. `viewModel` над ними посидит, подумает, запросит нужные данные, отбросит всю шелуху, и когда данные будут готовы для показа, закинет их во `Flow`, на который уже подписан `Fragment`.
Либо совсем не использовать `ViewModel` на этом экране, если он слишком прост, чтобы его усложнять слишком правильной архитектурой

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/CreateEditClaimCommentFragment.kt
> +        }
```suggestion
        with(binding.containerCustomAppBarIncludeOnFragmentCreateEditClaimComment) {
            mainMenuImageButton.visibility = View.GONE
            authorizationImageButton.visibility = View.GONE
            ourMissionImageButton.visibility = View.GONE
        }
```

2021-11-06 21:19 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/CreateEditClaimCommentFragment.kt
> +                //  Вставлять корректный creatorId вместо хардкода")
Спрячь всё это дальше в приложении. Ближе к данным. Ближе к тем местам, где реально надо будет что-то менять.

P.S.: В TODO-_**комментарии**_ совсем не обязательно ставить круглые скобки и кавычки, как при вызове _TODO-**функции**_ :hand_over_mouth:

2021-11-11 19:42 UTC, Dolgoff62 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +)
До авторизации оставлю. Чтобы не делать двойную работу

2021-11-11 19:46 UTC, Dolgoff62 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +        getItem(position)?.let {
исправлено

2021-11-25 08:35 UTC, nanstas commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +                        claimComment.creator.middleName?.let { middleName ->
Избавились от null, вложенность исчезла)

2021-11-25 08:36 UTC, nanstas commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +        }
Исправлено

2021-12-04 18:24 UTC, maks1596 requested changes

2021-12-04 18:24 UTC, maks1596 commented on app/lint.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Хочу узнать всю предысторию появления этого файлика 😊

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/AndroidManifest.xml
> +        tools:targetApi="m">
К чему эта целевая версия приписана?

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"
не надо экспортировать стартовую активити. и так должно работать

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +        getItem(position).let {
лучше не надо использовать `let` только для короткого имени `it`. `let` полезен с `nullable` значениями: `nullableVariable?.let { ... }`. в остальных случаях `let` не несёт в себе полезной нагрузки, и более читаемым вариантом будет просто положить значение в переменную с коротким именем (`it`, если так угодно)

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/adapter/NewsControlPanelAdapter.kt
> +                when (newsItemWithCreator.news.newsItem.publishEnabled) {
Заменить на `if else`

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dao/ClaimCommentDao.kt
> +    suspend fun insertComment(comments: List<ClaimCommentEntity>)
```suggestion
    suspend fun insertComments(comments: List<ClaimCommentEntity>)

```

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dao/ClaimDao.kt
> +        listStatuses: List<Claim.Status>
Неправильное название: либо `statusList`, либо `statuses`. `listStatuses` - это "статусы списка"

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dao/ClaimDao.kt
> +    suspend fun insertClaim(claims: List<ClaimEntity>)
```suggestion
    suspend fun insertClaims(claims: List<ClaimEntity>)

```

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dao/NewsDao.kt
> +interface NewsCategoryDao {
Лучше бы, наверное, в отдельный файлик

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/db/AppDb.kt
> +    abstract fun getNewsCategoryDao(): NewsCategoryDao
Если вдруг что, то можно и на свойства поменять 😉  
Например, `abstract val userDao: UserDao`. Так немного сэкономим на круглых скобках `()`

2021-12-04 18:24 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/claimRepository/ClaimRepository.kt
> +        claimComment: ClaimComment
что-то мне подсказывает, что надо делать 4 отдельных метода с собственным специфичным набором аргументов, а не пытаться всё свести под одну гребёнку

2021-12-04 22:22 UTC, maks1596 requested changes

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/claimRepository/ClaimRepository.kt
> +     * **/
Спасибо за комментарий. Теперь лучше видно, что надо делать 4 отдельных метода с собственным специфичным набором параметров, а не пытаться всё свести под одну гребёнку 😊

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dto/SplashScreen.kt
> +data class SplashScreen(
- `SplashScreenData`
- `SplashScreenConfiguration`

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/dto/SplashScreen.kt
> +    val image: Int,
Почему изображение - целое число?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/claimRepository/ClaimRepositoryImpl.kt
> +        listStatuses: List<Claim.Status>
либо `statuses`, либо `statusList`

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/newsRepository/NewsRepository.kt
> +    suspend fun modificationOfExistingNews(newsItem: News): News
`update` что ли? 🤔

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/newsRepository/NewsRepository.kt
> +    suspend fun changeIsOpen(newsItem: News)
можно комментарий? или метод переименовать? непонятное название

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/repository/newsRepository/NewsRepositoryImpl.kt
> +    }
Может метод тогда `update` назвать или `save`?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/AppActivity.kt
> +        // Костыль!!! Убрать!!! (Only for test!)
```suggestion
        // TODO Костыль!!! Убрать!!! (Only for test!)
```

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/AppActivity.kt
> +            )
По-моему я уже в репозитории видел этот список категорий, разве нет?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFilteringDialogFragment.kt
> +    private fun mutableListOfClaimStatus(dialogView: View): MutableList<Claim.Status> {
```suggestion
    private fun View.getCheckedStatuses(): List<Claim.Status> {
```

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFilteringDialogFragment.kt
> +            checkedStatusList.add(Claim.Status.CANCELLED)
```suggestion
        fun check(checkBoxId: Int, status: Claim.Status) {
            if (dialogView.findViewById<MaterialCheckBox>(checkBoxId).isChecked)
                 checkedStatusList.add(status)
        }
        check(R.id.item_filter_open, Claim.Status.OPEN)
        check(R.id.item_filter_in_progress, Claim.Status.IN_PROGRESS)
        check(R.id.item_filter_executed, Claim.Status.EXECUTED)
        check(R.id.item_filter_cancelled, Claim.Status.CANCELLED)
```

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/ClaimListFilteringDialogFragment.kt
> +            checkedStatusList.add(Claim.Status.CANCELLED)
Или что-нибудь подобное, чтобы компилятор обругивал на случай, если забудешь отразить в фильтре новый статус  
```suggestion
        for (status in Claim.Status.values()) {
             fun check(checkBoxId: Int) {
                 if (dialogView.findViewById<MaterialCheckBox>(checkBoxId).isChecked)
                     checkedStatusList.add(status)
             }
             when(status) {
                 Claim.Status.CANCELLED -> check(R.id.item_filter_cancelled)
                 Claim.Status.EXECUTED -> check(R.id.item_filter_executed)
                 Claim.Status.IN_PROGRESS -> check(R.id.item_filter_in_progress)
                 Claim.Status.OPEN -> check(R.id.item_filter_open)
             }
        }
```

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/CreateEditClaimFragment.kt
> +    //временно, пока нет авторизации
```suggestion
    // TODO временно, пока нет авторизации
```

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/res/menu/menu_main.xml
> +        android:visible="false"/>
Зачем эти пункты меню? 
1. без идентификаторов
2. невидимые

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/res/drawable/separator.xml
> +    tools:ignore="VectorRaster">
От чего этот `ignore`?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/res/drawable/ic_rectangle_381.xml
> +      android:fillColor="@android:color/transparent"/>
Прозрачный? Зачем нужен прозрачный `drawable`?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/res/drawable/ic_our_mission_21x23.xml
> +    android:viewportHeight="23">
так какой размер-то всё-таки? зачем значения расходятся? 😊

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/res/drawable/background_splash_screen_title_1.xml
> +<?xml version="1.0" encoding="utf-8"?>
6 файлов, которые отличаются только цветом. По сути тебе от фигуры внутри нужно только закругление в 5dp. Цвет можно попробовать наложиться через параметр `backgroundTint`

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/viewmodel/UserViewModel.kt
> +            userRepository.getAllUsers()
похоже на `refresh`

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/viewmodel/NewsViewModel.kt
> +    }
Перенеси это направление сортировки отдельно. Пригодится ещё ни раз

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/utils/Utils.kt
> +    }
?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/utils/Utils.kt
> +    }
Где-нибудь используется? Может заменить на глобальную функцию `internal fun EmptyClaimComment()`?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/utils/Utils.kt
> +    }
А если вынести из `Utils` и превратить в расширение для `EditText`?

```suggestion
internal fun EditText.setDate(calendar: Calendar) {
    val format = "dd.MM.yyyy"
    val simpleDateFormat = SimpleDateFormat(format, Locale.getDefault())
    setText(simpleDateFormat.format(calendar.time))
}
```

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/utils/Utils.kt
> +    }
А если вынести из `Utils` и превратить в расширение для `EditText`?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/utils/Utils.kt
> +    }
Ничего этот метод не сохраняет. Не надо никого обманывать. Переименовать

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/utils/Utils.kt
> +    }
Комментарий, кстати, тоже не в тему: нет в методе никакого знания про `picker`

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/utils/Utils.kt
> +            "dd.MM.yyy",
Выше был формат `dd.MM.yyyy`. Ничего не перепутано?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/utils/Utils.kt
> +                    }
А так случайно не работает?
```suggestion
                    result = hasTransport(NetworkCapabilities.TRANSPORT_WIFI or NetworkCapabilities.TRANSPORT_CELLULAR or NetworkCapabilities.TRANSPORT_VPN)
```

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/utils/Utils.kt
> +            cm?.run {
Вынеси проверку на `null` перед `if else` - она у тебя дважды происходит

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/SplashScreenActivity.kt
> +    private val splashscreenImages = listOf(
Уже не просто `images` 😊

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/SplashScreenActivity.kt
> +    private val splashscreenImage = splashscreenImages.random()
что-то как-то расточительно хранить целый список ради одного случайного элемента, не находишь?
```suggestion
    private val splashscreenImage by lazy { 
    listOf(
    SplashScreen(R.drawable.image_splashscreen_1,"Любая помощь важна и нужна", R.drawable.background_splash_screen_title_1, R.color.splash_screen_title_color_1),
        SplashScreen(R.drawable.image_splashscreen_2, "Бережное отношение к пациентам и их близким", R.drawable.background_splash_screen_title_2, R.color.splash_screen_title_color_2),
        SplashScreen(R.drawable.image_splashscreen_3, "Творческий и осознанный подход к жизни до конца", R.drawable.background_splash_screen_title_2, R.color.splash_screen_title_color_2),
        SplashScreen(R.drawable.image_splashscreen_4, "Ответственно и осознанно нести добро людям", R.drawable.background_splash_screen_title_4, R.color.splash_screen_title_color_4),
        SplashScreen(R.drawable.image_splashscreen_5, "Помощь – это создание комфорта для пациентов и их близких", R.drawable.background_splash_screen_title_5, R.color.splash_screen_title_color_5),
        SplashScreen(R.drawable.image_splashscreen_6, "Ответственно и осознанно нести добро людям", R.drawable.background_splash_screen_title_1, R.color.splash_screen_title_color_1),
        SplashScreen(R.drawable.image_splashscreen_7, "Творческий и осознанный подход к жизни пациента", R.drawable.background_splash_screen_title_6, R.color.splash_screen_title_color_6),
        SplashScreen(R.drawable.image_splashscreen_8, "Добро есть везде и во всех", R.drawable.background_splash_screen_title_4, R.color.splash_screen_title_color_4),
        SplashScreen(R.drawable.image_splashscreen_9, "Ответственная доброта", R.drawable.background_splash_screen_title_2, R.color.splash_screen_title_color_2),
        SplashScreen(R.drawable.image_splashscreen_10, "Создание физического и психологического пространства для завершения жизни", R.drawable.background_splash_screen_title_3, R.color.splash_screen_title_color_3),
        SplashScreen(R.drawable.image_splashscreen_11, "Творческий и осознанный подход к жизни пациента", R.drawable.background_splash_screen_title_6, R.color.splash_screen_title_color_6),
        SplashScreen(R.drawable.image_splashscreen_12, "Чем больше мы принимаем добра, тем больше отдаем", R.drawable.background_splash_screen_title_1, R.color.splash_screen_title_color_1),
        SplashScreen(R.drawable.image_splashscreen_13, "Хоспис – это воплощенная гуманность", R.drawable.background_splash_screen_title_5, R.color.splash_screen_title_color_5),
        SplashScreen(R.drawable.image_splashscreen_14, "Хоспис — это призвание и служение человечеству", R.drawable.background_splash_screen_title_6, R.color.splash_screen_title_color_6),
        SplashScreen(R.drawable.image_splashscreen_15, "Хоспис – это наука помощи и искусство ухода", R.drawable.background_splash_screen_title_1, R.color.splash_screen_title_color_1),
        SplashScreen(R.drawable.image_splashscreen_16, "Ответственно и осознанно нести добро людям", R.drawable.background_splash_screen_title_3, R.color.splash_screen_title_color_3),
        SplashScreen(R.drawable.image_splashscreen_17, "Хоспис – это компетентная помощь и любовь к пациентам", R.drawable.background_splash_screen_title_4, R.color.splash_screen_title_color_4)
    ).random()
    }
```

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/SplashScreenActivity.kt
> +        makeFullScreen()
В `onDestroy` обратно "разфулскринивать" не нужно?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/SplashScreenActivity.kt
> +        SplashScreen(R.drawable.image_splashscreen_1,"Любая помощь важна и нужна", R.drawable.background_splash_screen_title_1, R.color.splash_screen_title_color_1),
Всем ресурсных строк за мой счёт!

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/NewsListFragment.kt
> +//                }
Удалить закомментированный код

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/NewsListFragment.kt
> +                )
Можно без задержки попробовать? Мне казалось, что этот код работал
```js
binding.containerListNewsInclude.newsListRecyclerView.post {
    binding.containerListNewsInclude.newsListRecyclerView.scrollToPosition(
        0
    )
}
```
Или вот ещё, как по мне, интересный вариант для проверки на работоспособность
```js
adapter.submitList(newList) {
    binding.containerListNewsInclude.newsListRecyclerView.scrollToPosition(
        0
    )
}
```

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/NewsListFragment.kt
> +        mainMenu.menu.removeItem(R.id.menu_item_news)
Зачем удалять элемент из меню? Может нам тогда не подходит это меню, если приходится удалять из него пункты?

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/NewsControlPanelFragment.kt
> +                    .create()
Диалог можно лениво создать один раз

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/NewsControlPanelFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launchWhenStarted {
Можно в `onCreate` перетащить - здесь не нужно ничего от `view`

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/NewsControlPanelFragment.kt
> +        val activity = activity ?: return
`activity` в `onViewCreated` уже должна быть. используй `requireActivity()`

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/NewsControlPanelFragment.kt
> +                    R.id.action_newsControlPanelFragment_to_createEditNewsFragment
Без идентификаторов, пожалуйста. Надёэнее заменить на сгенерированные классы. Если у этого направления навигации появятся аргументы то сгенерированный `Direction` тебе обругает за не переданные аргументы, а `navigate` с идентификатором - нет, просто свалится приложение в runtime

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/CreateEditNewsFragment.kt
> +    }
Вынеси наружу из этого класса и сделай глобальным расширением для `Fragment`

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/CreateEditNewsFragment.kt
> +    }
Только имя у него на самом деле просто `showToast` - к ошибке данный метод не причастен

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/FilterNewsListFragment.kt
> +        val calendar = Calendar.getInstance()
Из-за того, что используется один и тот же инстанс `Calendar` как в качестве агрегатора результата выбора `DatePicker`, так и для его первичной установки, можно достичь интересного результата. Например:

№ | Действие | Результат 
--- | --- | ---
1 | Нажать на дату начала | Видим сегодняшнюю дату
2 | Выбрать "вчера" | Вчерашняя дата отобразилась в поле "Дата начала"
3 | Нажать на дату окончания | Видим вчерашнюю дату. Настораживает, но не критично
4 | Выбрать "завтра" | Завтрашняя дата отобразилась в поле "Дата окончания"
5 | Нажать на дату начала | Видим завтрашнюю дату

Ожидаемый результат:
> Видим вчерашнюю дату, потому что она отображается в нажатом поле "Дата начала"

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/MainFragment.kt
> +                    findNavController().navigate(R.id.action_mainFragment_to_claimListFragment)
Заменить идентификаторы на сгенерированные классы `Directions` - надёжнее будет

2021-12-04 22:22 UTC, maks1596 commented on app/src/main/java/ru/netology/fmhandroid/ui/MainFragment.kt
> +                    View.GONE -> {
1. Я бы лучше наоборот ориентировался на `View.VISIBLE`, потому что есть ещё сродний `View.GONE` вариант - `View.INVISIBLE`
2. Этот `when` лучше заменить на `if else`. От `when` тут пользы никакой.
3. Лучше не ориентироваться на видимость другой `view` в таких случаях. Правильнее будет ориентироваться на текущее состояние экрана, которое хранится во `viewModel`

2021-12-14 14:14 UTC, nanstas commented on app/src/main/java/ru/netology/fmhandroid/adapter/ClaimCommentListAdapter.kt
> +        getItem(position).let {
положил в переменную.

2022-02-21 18:45 UTC, merged